import { act, fireEvent, render, screen, waitFor } from "@testing-library/react"
import { afterEach, beforeEach, expect, it, vi } from "vitest"
import { useRuntimePreferencesStore } from "@/state/runtimePreferencesStore"
import { useHostStore } from "@/state/hostStore"
import { useUiStore } from "@/state/uiStore"
import { useSshStore } from "@/state/sshStore"
import type { RuntimeBinaryCheck } from "@/lib/herdrTypes"
const ipc = vi.hoisted(() => ({ get: vi.fn(), set: vi.fn(), check: vi.fn(), distros: vi.fn(), remote: vi.fn(), copy: vi.fn() }))
vi.mock("@/lib/herdrIpc", () => ({ herdrBinarySourceGet: ipc.get, herdrBinarySourceSet: ipc.set, herdrBinarySourceCheck: ipc.check }))
vi.mock("@/lib/hostIpc", () => ({ checkHostRuntime: ipc.remote, wslDistributions: ipc.distros }))
vi.mock("@/lib/platform", () => ({ isWindowsPlatform: () => true }))
vi.mock("@tauri-apps/plugin-clipboard-manager", () => ({ writeText: ipc.copy }))
import { HerdrSettingsSection } from "./HerdrSettingsSection"
const check: RuntimeBinaryCheck = { reportedBinary: null, binary: "C:\\Yuzora\\herdr.exe", clientVersion: "0.9.0", clientProtocol: 22, schemaProtocol: 22, missingMethods: [], canApply: true, sessions: [{ name: "default", running: true, serverVersion: "0.9.0", serverProtocol: 22, compatible: true, socket: "native.sock" }] }
beforeEach(() => {
  vi.resetAllMocks()
  const values = new Map<string, string>()
  vi.stubGlobal("localStorage", { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value) })
  useRuntimePreferencesStore.setState({ wslEnabled: false })
  useHostStore.setState({ configs: {}, hosts: {} })
  useSshStore.setState({ hosts: [], sessions: {} })
  useUiStore.setState({ settingsHostId: null })
  ipc.get.mockResolvedValue({ configured: "default", active: "global", available: true, path: "C:\\installed\\herdr.exe", version: "0.8.2", protocol: 20, configuredPath: "C:\\Yuzora\\herdr.exe", restartRequired: true })
  ipc.check.mockResolvedValue(check)
  ipc.distros.mockResolvedValue([{ hostId: "wsl-a", name: "Ubuntu", version: 2 }])
  ipc.copy.mockResolvedValue(undefined)
})
afterEach(() => vi.unstubAllGlobals())
it("shows the active Windows client and saved target, and discovers WSL only after opt-in", async () => {
  render(<HerdrSettingsSection />)
  expect(await screen.findByText("C:\\installed\\herdr.exe")).toBeInTheDocument()
  expect(screen.getByText("0.8.2 · protocol 20")).toBeInTheDocument()
  expect(screen.getByText("C:\\Yuzora\\herdr.exe")).toBeInTheDocument()
  expect(screen.getByRole("switch")).not.toBeChecked()
  expect(ipc.distros).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole("switch"))
  await waitFor(() => expect(ipc.distros).toHaveBeenCalledOnce())
})
it("blocks applying a mismatched client without changing the saved source", async () => {
  ipc.check.mockResolvedValue({ ...check, canApply: false, clientVersion: "0.8.2", clientProtocol: 20, sessions: [{ ...check.sessions[0], compatible: false }] })
  render(<HerdrSettingsSection />)
  fireEvent.click(await screen.findByRole("button", { name: "Check / detect again" }))
  expect(await screen.findByText("Cannot apply this selection")).toBeInTheDocument()
  expect(screen.getByRole("button", { name: "Apply source" })).toBeDisabled()
  expect(screen.getByText("Server: 0.9.0 · protocol 22")).toBeInTheDocument()
  expect(ipc.set).not.toHaveBeenCalled()
})
it("rechecks on apply and reports a backend rejection without claiming success", async () => {
  ipc.set.mockRejectedValue(new Error("server changed during check"))
  render(<HerdrSettingsSection />)
  fireEvent.click(await screen.findByRole("button", { name: "Check / detect again" }))
  const apply = screen.getByRole("button", { name: "Apply source" })
  await waitFor(() => expect(apply).toBeEnabled())
  fireEvent.click(apply)
  expect(await screen.findByText(/server changed during check/)).toBeInTheDocument()
  expect(ipc.set).toHaveBeenCalledWith("default", undefined)
  expect(ipc.get).toHaveBeenCalledOnce()
})
it("targets a disabled WSL host without probing its binary", () => {
  useUiStore.setState({ settingsHostId: "wsl-a" })
  useHostStore.setState({ configs: { "wsl-a": { hostId: "wsl-a", label: "Ubuntu", kind: "wsl", distro: "Ubuntu", binary: "/old/herdr", helper: "/helper" } } })
  render(<HerdrSettingsSection />)
  expect(screen.getByText("WSL HERDR is disabled")).toBeInTheDocument()
  expect(ipc.remote).not.toHaveBeenCalled()
  expect(ipc.get).not.toHaveBeenCalled()
})
it("shows old selected WSL client separately from the new managed candidate and copies both", async () => {
  useRuntimePreferencesStore.setState({ wslEnabled: true })
  useUiStore.setState({ settingsHostId: "wsl-a" })
  useHostStore.setState({ configs: { "wsl-a": { hostId: "wsl-a", label: "Ubuntu", kind: "wsl", distro: "Ubuntu", binary: "/old/herdr", helper: "/helper", selection: { source: "default" } } } })
  ipc.remote.mockImplementation((_id, _target, selection) => Promise.resolve({ binary: selection.customPath ?? "/new/herdr", managedVersion: "0.9.0", managedProtocol: 22, artifactIdentity: "new", requiresInstall: false, check: selection.source === "custom" ? { ...check, binary: "/old/herdr", clientVersion: "0.8.2", clientProtocol: 20, canApply: false } : { ...check, binary: "/new/herdr" } }))
  render(<HerdrSettingsSection />)
  fireEvent.click(screen.getByRole("button", { name: "Check / detect again" }))
  expect(await screen.findByText("0.8.2 · protocol 20")).toBeInTheDocument()
  expect(screen.getByText("0.9.0 · protocol 22")).toBeInTheDocument()
  expect(screen.getByText("Host tool update available")).toBeInTheDocument()
  fireEvent.click(screen.getByRole("button", { name: "Copy diagnostics" }))
  await waitFor(() => expect(ipc.copy).toHaveBeenCalledOnce())
  expect(JSON.parse(ipc.copy.mock.calls[0][0])).toMatchObject({ hostId: "wsl-a", current: { check: { binary: "/old/herdr", clientProtocol: 20 } }, target: { check: { binary: "/new/herdr", clientProtocol: 22 } } })
})
it("ignores a delayed check after changing the selected host", async () => {
  let resolve!: (result: RuntimeBinaryCheck) => void
  ipc.check.mockReturnValue(new Promise(done => { resolve = done }))
  const mounted = render(<HerdrSettingsSection />)
  fireEvent.click(await screen.findByRole("button", { name: "Check / detect again" }))
  act(() => useUiStore.setState({ settingsHostId: "unknown" }))
  await act(async () => resolve(check))
  expect(screen.queryByRole("button", { name: "Apply source" })).not.toBeInTheDocument()
  mounted.unmount()
})
