import { act, fireEvent, render, screen, waitFor } from "@testing-library/react"
import { afterEach, beforeEach, expect, it, vi } from "vitest"
import { useRuntimePreferencesStore } from "@/state/runtimePreferencesStore"
import { useHostStore } from "@/state/hostStore"
import { useUiStore } from "@/state/uiStore"
import { useSshStore } from "@/state/sshStore"
import { useWorkspaceStore } from "@/state/workspaceStore"
import type { RuntimeBinaryCheck } from "@/lib/herdrTypes"
const ipc = vi.hoisted(() => ({ get: vi.fn(), set: vi.fn(), check: vi.fn(), distros: vi.fn(), remote: vi.fn(), copy: vi.fn(), relaunch: vi.fn(), prefsSet: vi.fn() }))
vi.mock("@tauri-apps/plugin-process", () => ({ relaunch: ipc.relaunch }))
vi.mock("@/lib/runtimePreferencesIpc", () => ({ runtimePreferencesGet: vi.fn(), runtimePreferencesSet: ipc.prefsSet }))
vi.mock("@/lib/herdrIpc", () => ({ herdrBinarySourceGet: ipc.get, herdrBinarySourceSet: ipc.set, herdrBinarySourceCheck: ipc.check }))
vi.mock("@/lib/hostIpc", () => ({ checkHostRuntime: ipc.remote, wslDistributions: ipc.distros }))
vi.mock("@/lib/platform", () => ({ isWindowsPlatform: () => true }))
vi.mock("@tauri-apps/plugin-clipboard-manager", () => ({ writeText: ipc.copy }))
import { HerdrSettingsSection } from "./HerdrSettingsSection"
const check: RuntimeBinaryCheck = { reportedBinary: null, binary: "C:\\Yuzora\\herdr.exe", clientVersion: "0.9.0", clientProtocol: 22, schemaProtocol: 22, missingMethods: [], canApply: true, sessions: [{ name: "default", running: true, serverVersion: "0.9.0", serverProtocol: 22, compatible: true, socket: "native.sock" }] }
beforeEach(() => {
  vi.resetAllMocks()
  const values = new Map<string, string>()
  vi.stubGlobal("localStorage", { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value) })
  useRuntimePreferencesStore.setState({ wslEnabled: false })
  useHostStore.setState({ configs: {}, hosts: {} })
  useSshStore.setState({ hosts: [], sessions: {} })
  useUiStore.setState({ settingsHostId: null })
  ipc.get.mockResolvedValue({ configured: "default", active: "global", available: true, path: "C:\\installed\\herdr.exe", version: "0.8.2", protocol: 20, configuredPath: "C:\\Yuzora\\herdr.exe", restartRequired: true })
  ipc.check.mockResolvedValue(check)
  ipc.distros.mockResolvedValue([{ hostId: "wsl-a", name: "Ubuntu", version: 2 }])
  ipc.copy.mockResolvedValue(undefined)
  ipc.relaunch.mockResolvedValue(undefined)
  ipc.prefsSet.mockImplementation(async (value: boolean) => ({ wslEnabled: value }))
  useWorkspaceStore.setState({ groups: [{ tabs: [], activePath: null }] } as never)
})
afterEach(() => vi.unstubAllGlobals())
it("shows the active Windows client and saved target, and discovers WSL only after opt-in", async () => {
  render(<HerdrSettingsSection />)
  expect(await screen.findByText("C:\\installed\\herdr.exe")).toBeInTheDocument()
  expect(screen.getByText("0.8.2 · protocol 20")).toBeInTheDocument()
  expect(screen.getByText("C:\\Yuzora\\herdr.exe")).toBeInTheDocument()
  expect(screen.getByRole("switch")).not.toBeChecked()
  expect(ipc.distros).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole("switch"))
  await waitFor(() => expect(ipc.distros).toHaveBeenCalledOnce())
})
it("blocks applying a mismatched client without changing the saved source", async () => {
  ipc.check.mockResolvedValue({ ...check, canApply: false, clientVersion: "0.8.2", clientProtocol: 20, sessions: [{ ...check.sessions[0], compatible: false }] })
  render(<HerdrSettingsSection />)
  fireEvent.click(await screen.findByRole("button", { name: "Check / detect again" }))
  expect(await screen.findByText("Cannot apply this selection")).toBeInTheDocument()
  expect(screen.getByRole("button", { name: "Apply source" })).toBeDisabled()
  expect(screen.getByText("Server: 0.9.0 · protocol 22")).toBeInTheDocument()
  expect(ipc.set).not.toHaveBeenCalled()
})
const changed = vi.fn()
beforeEach(() => { changed.mockClear(); window.addEventListener("yuzora:herdr-binary-source-changed", changed) })
afterEach(() => window.removeEventListener("yuzora:herdr-binary-source-changed", changed))

it("dispatches the binary-source-changed event only after a successful apply", async () => {
  ipc.set.mockResolvedValue({ configured: "default", restartRequired: false })
  render(<HerdrSettingsSection />)
  fireEvent.click(await screen.findByRole("button", { name: "Check / detect again" }))
  const apply = screen.getByRole("button", { name: "Apply source" })
  await waitFor(() => expect(apply).toBeEnabled())
  fireEvent.click(apply)
  await waitFor(() => expect(changed).toHaveBeenCalledOnce())
})

it("rechecks on apply and reports a backend rejection without claiming success", async () => {
  ipc.set.mockRejectedValue(new Error("server changed during check"))
  render(<HerdrSettingsSection />)
  fireEvent.click(await screen.findByRole("button", { name: "Check / detect again" }))
  const apply = screen.getByRole("button", { name: "Apply source" })
  await waitFor(() => expect(apply).toBeEnabled())
  fireEvent.click(apply)
  expect(await screen.findByText(/server changed during check/)).toBeInTheDocument()
  expect(ipc.set).toHaveBeenCalledWith("default", undefined)
  expect(ipc.get).toHaveBeenCalledOnce()
  expect(changed).not.toHaveBeenCalled()
})
it("targets a disabled WSL host without probing its binary", () => {
  useUiStore.setState({ settingsHostId: "wsl-a" })
  useHostStore.setState({ configs: { "wsl-a": { hostId: "wsl-a", label: "Ubuntu", kind: "wsl", distro: "Ubuntu", binary: "/old/herdr", helper: "/helper" } } })
  render(<HerdrSettingsSection />)
  expect(screen.getByText("WSL HERDR is disabled")).toBeInTheDocument()
  expect(ipc.remote).not.toHaveBeenCalled()
  expect(ipc.get).not.toHaveBeenCalled()
})
it("shows old selected WSL client separately from the new managed candidate and copies both", async () => {
  useRuntimePreferencesStore.setState({ wslEnabled: true })
  useUiStore.setState({ settingsHostId: "wsl-a" })
  useHostStore.setState({ configs: { "wsl-a": { hostId: "wsl-a", label: "Ubuntu", kind: "wsl", distro: "Ubuntu", binary: "/old/herdr", helper: "/helper", selection: { source: "default" } } } })
  ipc.remote.mockImplementation((_id, _target, selection) => Promise.resolve({ binary: selection.customPath ?? "/new/herdr", managedVersion: "0.9.0", managedProtocol: 22, artifactIdentity: "new", requiresInstall: false, check: selection.source === "custom" ? { ...check, binary: "/old/herdr", clientVersion: "0.8.2", clientProtocol: 20, canApply: false } : { ...check, binary: "/new/herdr" } }))
  render(<HerdrSettingsSection />)
  fireEvent.click(screen.getByRole("button", { name: "Check / detect again" }))
  expect(await screen.findByText("0.8.2 · protocol 20")).toBeInTheDocument()
  expect(screen.getByText("0.9.0 · protocol 22")).toBeInTheDocument()
  expect(screen.getByText("Host tool update available")).toBeInTheDocument()
  fireEvent.click(screen.getByRole("button", { name: "Copy diagnostics" }))
  await waitFor(() => expect(ipc.copy).toHaveBeenCalledOnce())
  expect(JSON.parse(ipc.copy.mock.calls[0][0])).toMatchObject({ hostId: "wsl-a", current: { check: { binary: "/old/herdr", clientProtocol: 20 } }, target: { check: { binary: "/new/herdr", clientProtocol: 22 } } })
})
it("ignores a delayed check after changing the selected host", async () => {
  let resolve!: (result: RuntimeBinaryCheck) => void
  ipc.check.mockReturnValue(new Promise(done => { resolve = done }))
  const mounted = render(<HerdrSettingsSection />)
  fireEvent.click(await screen.findByRole("button", { name: "Check / detect again" }))
  act(() => useUiStore.setState({ settingsHostId: "unknown" }))
  await act(async () => resolve(check))
  expect(screen.queryByRole("button", { name: "Apply source" })).not.toBeInTheDocument()
  mounted.unmount()
})

const customInfo = { configured: "custom", active: "default", available: true, path: "C:\\Yuzora\\herdr.exe", version: "0.9.3", protocol: 22, customPath: '"C:\\Program Files\\Herdr\\herdr.exe"', restartRequired: false }
it("hands the backend a clean path when the pasted custom path is quoted and contains spaces", async () => {
  ipc.get.mockResolvedValue(customInfo)
  render(<HerdrSettingsSection />)
  fireEvent.click(await screen.findByRole("button", { name: "Check / detect again" }))
  await waitFor(() => expect(ipc.check).toHaveBeenCalledWith("custom", "C:\\Program Files\\Herdr\\herdr.exe"))
  const input = screen.getByLabelText("Custom executable path") as HTMLInputElement
  fireEvent.change(input, { target: { value: '  "D:\\My Tools\\herdr.exe"  ' } })
  expect(input.value).toBe('  "D:\\My Tools\\herdr.exe"  ')
  fireEvent.blur(input)
  expect(input.value).toBe("D:\\My Tools\\herdr.exe")
})
it("shows a restart button that relaunches, and disables it while a document is dirty", async () => {
  render(<HerdrSettingsSection />)
  const button = await screen.findByRole("button", { name: "Restart Yuzora now" })
  expect(button).toBeEnabled()
  fireEvent.click(button)
  await waitFor(() => expect(ipc.relaunch).toHaveBeenCalledOnce())
})
it("blocks the restart button while an editor tab has unsaved changes", async () => {
  useWorkspaceStore.setState({ groups: [{ tabs: [{ path: "/a", dirty: true }], activePath: "/a" }] } as never)
  render(<HerdrSettingsSection />)
  const button = await screen.findByRole("button", { name: "Restart Yuzora now" })
  expect(button).toBeDisabled()
  expect(screen.getByText("Save or discard unsaved editor changes before restarting.")).toBeInTheDocument()
  fireEvent.click(button)
  expect(ipc.relaunch).not.toHaveBeenCalled()
})
const missingInfo = { ...customInfo, available: false, reason: "herdr-custom-path-not-executable: C:\\gone\\herdr.exe" }
it("offers to switch a missing custom binary back to the bundled version and restarts", async () => {
  ipc.get.mockResolvedValueOnce(missingInfo).mockResolvedValue({ ...customInfo, configured: "default", available: true, restartRequired: true })
  ipc.set.mockResolvedValue({ configured: "default", restartRequired: true })
  render(<HerdrSettingsSection />)
  expect(await screen.findByText(/custom HERDR path can't be run/)).toBeInTheDocument()
  fireEvent.click(screen.getByRole("button", { name: "Switch back to bundled version and restart" }))
  await waitFor(() => expect(ipc.relaunch).toHaveBeenCalledOnce())
  expect(ipc.set).toHaveBeenCalledWith("default")
  expect(changed).toHaveBeenCalledOnce()
})
it("saves but does not relaunch when documents are dirty while switching back to bundled", async () => {
  useWorkspaceStore.setState({ groups: [{ tabs: [{ path: "/a", dirty: true }], activePath: "/a" }] } as never)
  ipc.get.mockResolvedValueOnce(missingInfo).mockResolvedValue({ ...customInfo, configured: "default", available: true, restartRequired: true })
  ipc.set.mockResolvedValue({ configured: "default", restartRequired: true })
  render(<HerdrSettingsSection />)
  fireEvent.click(await screen.findByRole("button", { name: "Switch back to bundled version" }))
  expect(await screen.findByText(/restart Yuzora manually/)).toBeInTheDocument()
  expect(ipc.set).toHaveBeenCalledWith("default")
  expect(ipc.relaunch).not.toHaveBeenCalled()
})
it("does not offer the revert for unrelated errors", async () => {
  ipc.get.mockResolvedValue({ ...customInfo, available: false, reason: "herdr-socket-timeout" })
  render(<HerdrSettingsSection />)
  expect(await screen.findByText("The HERDR server didn't respond in time.")).toBeInTheDocument()
  expect(screen.queryByRole("button", { name: /Switch back to bundled/ })).not.toBeInTheDocument()
})
it("keeps the WSL switch off and reports the error when the backend refuses to save", async () => {
  ipc.prefsSet.mockRejectedValue("runtime-preferences-write-failed")
  render(<HerdrSettingsSection />)
  fireEvent.click(await screen.findByRole("switch"))
  expect(await screen.findByText("runtime-preferences-write-failed")).toBeInTheDocument()
  expect(screen.getByRole("switch")).not.toBeChecked()
})
