import { afterEach, expect, it, vi } from 'vitest'
import { createPaneScrollController } from './herdrScrollController'
const base = { offsetFromBottom: 0, maxOffsetFromBottom: 1000, viewportRows: 24 }
afterEach(() => vi.useRealTimers())
it('quietly retries busy with the latest target, preserving cadence and eventual final position', async () => {
  vi.useFakeTimers()
  const error = vi.fn(), change = vi.fn()
  const write = vi.fn().mockRejectedValueOnce('host-request-limit').mockImplementation(async offset => ({ ...base, offsetFromBottom: offset }))
  const c = createPaneScrollController({ read: async () => base, write, change, error, allowed: () => true })
  await c.refresh(); c.move(20)
  await vi.advanceTimersByTimeAsync(10)
  c.move(70)
  await vi.advanceTimersByTimeAsync(24)
  expect(write.mock.calls.map(([offset]) => offset)).toEqual([20, 70])
  expect(error).not.toHaveBeenCalled()
  expect(change).toHaveBeenLastCalledWith({ ...base, offsetFromBottom: 70 })
  c.dispose()
})
it('reports sustained busy once after a bounded retry deadline', async () => {
  vi.useFakeTimers()
  const error = vi.fn(), write = vi.fn().mockRejectedValue('host-request-limit')
  const c = createPaneScrollController({ read: async () => base, write, error, change: vi.fn(), allowed: () => true })
  await c.refresh(); c.move(50)
  await vi.advanceTimersByTimeAsync(1500)
  expect(error).toHaveBeenCalledTimes(1)
  expect(write.mock.calls.length).toBeLessThanOrEqual(10)
  c.dispose(); expect(vi.getTimerCount()).toBe(0)
})
it.each(['permission denied', 'unknown_method', 'host-disconnected', 'host-request-timeout'])('never retries a permanent or ambiguous write failure: %s', async reason => {
  vi.useFakeTimers()
  const error = vi.fn(), write = vi.fn(() => { throw new Error(reason) })
  const c = createPaneScrollController({ read: async () => base, write, error, change: vi.fn(), allowed: () => true })
  await c.refresh(); c.move(5); c.move(10)
  await vi.advanceTimersByTimeAsync(1000)
  expect(error).toHaveBeenCalledOnce(); expect(write).toHaveBeenCalledOnce()
  c.dispose()
})
it('ignores stale shrinking overflow until the final acknowledgement', async () => {
  let ack!: (value: typeof base) => void
  const change = vi.fn(), write = vi.fn().mockImplementationOnce(() => new Promise(resolve => { ack = resolve })).mockImplementation(async offset => ({ ...base, maxOffsetFromBottom: 500, offsetFromBottom: Math.min(offset, 500) }))
  const c = createPaneScrollController({ read: async () => base, write, change, allowed: () => true })
  await c.refresh(); c.move(10); c.move(900)
  ack({ ...base, offsetFromBottom: 10, maxOffsetFromBottom: 100 })
  await Promise.resolve()
  expect(change).toHaveBeenLastCalledWith({ ...base, offsetFromBottom: 900 })
  await vi.waitFor(() => expect(change).toHaveBeenLastCalledWith({ ...base, maxOffsetFromBottom: 500, offsetFromBottom: 500 }))
  c.dispose()
})
it('probes an unsupported endpoint only once per controller generation', async () => {
  const read = vi.fn().mockRejectedValue('unknown_method'), error = vi.fn()
  const c = createPaneScrollController({ read, write: vi.fn(), error, change: vi.fn(), allowed: () => true })
  await c.refresh(); await c.refresh(); c.scroll(-10)
  expect(read).toHaveBeenCalledOnce(); expect(error).toHaveBeenCalledOnce()
  c.reset(); await c.refresh(); expect(read).toHaveBeenCalledTimes(2); c.dispose()
})
