// fixtures/gen-preview-fixtures.ts - bun run fixtures/gen-preview-fixtures.ts
// Creates fixtures/out/preview-demo for M4 preview GUI acceptance.
// Idempotent: removes the generated project before recreating it.

import { rmSync, mkdirSync, writeFileSync } from "node:fs"
import { join, dirname } from "node:path"

const root = join("fixtures", "out", "preview-demo")

function write(rel: string, content: string) {
    const path = join(root, rel)
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
}

const packageJson = {
    name: "yuzora-preview-demo",
    private: true,
    type: "module",
    scripts: {
        dev: "bun run server.ts",
        "dev:blocked": "bun run blocked-server.ts"
    }
}

const serverTs = `const port = Number(process.env.PORT ?? "5173")
const hostname = process.env.HOST ?? "127.0.0.1"

const files = {
    "/": "index.html",
    "/index.html": "index.html",
    "/page-a.html": "page-a.html",
    "/page-b.html": "page-b.html"
}

const server = Bun.serve({
    hostname,
    port,
    async fetch(req) {
        const url = new URL(req.url)
        if (url.pathname === "/health") {
            return Response.json({ ok: true, fixture: "preview-demo", port })
        }

        const file = files[url.pathname as keyof typeof files]
        if (!file) return new Response("Not found", { status: 404 })

        return new Response(await Bun.file(file).text(), {
            headers: { "content-type": "text/html; charset=utf-8" }
        })
    }
})

console.log("preview-demo dev server running")
console.log(\`  url: http://\${server.hostname}:\${server.port}\`)
console.log("  pages: /, /page-a.html, /page-b.html, /health")
`

const blockedServerTs = `const port = Number(process.env.PORT ?? "5174")
const hostname = process.env.HOST ?? "127.0.0.1"

const server = Bun.serve({
    hostname,
    port,
    fetch() {
        return new Response(\`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Yuzora X-Frame-Options Blocked Fixture</title>
</head>
<body>
  <main>
    <h1>X-Frame-Options blocked fixture</h1>
    <p>This page intentionally sends X-Frame-Options: DENY.</p>
  </main>
</body>
</html>\`, {
            headers: {
                "content-type": "text/html; charset=utf-8",
                "x-frame-options": "DENY"
            }
        })
    }
})

console.log("preview-demo blocked-frame server running")
console.log(\`  url: http://\${server.hostname}:\${server.port}\`)
console.log("  header: X-Frame-Options: DENY")
`

const indexHtml = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Yuzora M4 Preview Demo</title>
  <style>
    :root {
      color: #16211c;
      background: #f7f8f3;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }

    body {
      margin: 0;
      min-height: 100vh;
      display: grid;
      place-items: center;
    }

    main {
      width: min(720px, calc(100vw - 48px));
      border: 1px solid #b9c6bd;
      background: #ffffff;
      padding: 32px;
    }

    h1 {
      margin: 0 0 12px;
      font-size: 28px;
    }

    p {
      line-height: 1.5;
    }

    nav {
      display: flex;
      gap: 12px;
      flex-wrap: wrap;
      margin-top: 20px;
    }
  </style>
</head>
<body>
  <main>
    <h1>MVP-8 Preview Demo</h1>
    <p>This page is generated by fixtures/gen-preview-fixtures.ts for Yuzora M4 manual acceptance.</p>
    <p data-testid="preview-demo-marker">Recognizable fixture marker: YUZORA_M4_PREVIEW_DEMO</p>
    <nav>
      <a href="/page-a.html">Open page A</a>
      <a href="/page-b.html">Open page B</a>
      <a href="/health">Health JSON</a>
    </nav>
  </main>
  <script>
    console.log("Yuzora M4 preview-demo loaded", {
      title: document.title,
      marker: "YUZORA_M4_PREVIEW_DEMO",
      path: location.pathname
    })
  </script>
</body>
</html>
`

const pageAHtml = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Yuzora Preview Demo - Page A</title>
</head>
<body>
  <main>
    <h1>Preview Demo Page A</h1>
    <p>Use this page to exercise preview back and forward navigation.</p>
    <a href="/page-b.html">Go to page B</a>
    <a href="/">Back to home</a>
  </main>
  <script>console.log("Yuzora preview-demo page A loaded")</script>
</body>
</html>
`

const pageBHtml = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Yuzora Preview Demo - Page B</title>
</head>
<body>
  <main>
    <h1>Preview Demo Page B</h1>
    <p>Use this page to exercise preview reload and history controls.</p>
    <a href="/page-a.html">Go to page A</a>
    <a href="/">Back to home</a>
  </main>
  <script>console.log("Yuzora preview-demo page B loaded")</script>
</body>
</html>
`

const readme = `# Yuzora M4 Preview Demo Fixture

Run the normal preview target:

\`\`\`bash
bun run dev
\`\`\`

Run the X-Frame-Options blocked target:

\`\`\`bash
bun run dev:blocked
\`\`\`

Use \`PORT=<port>\` to override either server port.
`

const files: Record<string, string> = {
    "package.json": `${JSON.stringify(packageJson, null, 2)}\n`,
    "server.ts": serverTs,
    "blocked-server.ts": blockedServerTs,
    "index.html": indexHtml,
    "page-a.html": pageAHtml,
    "page-b.html": pageBHtml,
    "README.md": readme
}

rmSync(root, { recursive: true, force: true })
for (const [rel, content] of Object.entries(files)) write(rel, content)

console.log("preview-demo fixture ready:")
console.log(`  path:  ${root}`)
console.log("  run:   cd fixtures/out/preview-demo && bun run dev")
console.log("  xfo:   cd fixtures/out/preview-demo && bun run dev:blocked")
console.log("  pages:")
for (const rel of Object.keys(files)) console.log(`    ${rel}`)
