// Generated by scripts/generate-brand-assets.py; edit the master there.
export const BRAND_PATHS = [
  {
    "fill": "var(--logo-silver, #cbd5e1)",
    "d": "M34 32H73Q77 32 80 35L120 77Q124 81 124 86V109Q124 117 118 111L91 83H78Q73 83 70 79L30 39Q24 32 34 32Z"
  },
  {
    "fill": "var(--logo-fold, #8caab7)",
    "d": "M91 83H124V109Q124 117 118 111Z"
  },
  {
    "fill": "var(--logo-primary, #3b82f6)",
    "d": "M142 88L190 36Q194 32 199 32H231Q239 32 234 39L149 132Q142 139 136 132V101Q136 94 142 88Z"
  },
  {
    "fill": "var(--logo-secondary, #14b8a6)",
    "d": "M96 111L132 148Q136 152 136 158V224Q136 232 130 226L92 186Q88 182 88 176V115Q88 107 96 111Z"
  }
] as const
